using Microsoft.Web.WebView2.Core;
using System.Globalization;
using System.Text.Json;

namespace WhisperWinForms
{
    public sealed partial class LoginForm : Form
    {
        private readonly string _startUrl;
        private BrowserLoginResult? _result;

        public BrowserLoginResult? Result => _result;

        public LoginForm(string startUrl)
        {
            _startUrl = startUrl;
            InitializeComponent();
        }

        private async void LoginForm_Load(object? sender, EventArgs e)
        {
            try
            {
                await _webView.EnsureCoreWebView2Async();
                _webView.CoreWebView2.Navigate(_startUrl);
            }
            catch (WebView2RuntimeNotFoundException)
            {
                MessageBox.Show(this, GlobalResources.GetString("messageWebView2RuntimeMissing"), GlobalResources.GetString("titleWebView2RuntimeMissing"), MessageBoxButtons.OK, MessageBoxIcon.Error);
                DialogResult = DialogResult.Abort;
            }
            catch (Exception exception)
            {
                MessageBox.Show(this, exception.Message, GlobalResources.GetString("titleLoginPageError"), MessageBoxButtons.OK, MessageBoxIcon.Error);
                DialogResult = DialogResult.Abort;
            }
        }

        private async void ButtonUseSession_Click(object? sender, EventArgs e)
        {
            if (_webView.CoreWebView2 == null)
            {
                return;
            }

            try
            {
                string cookieFilePath = Path.Combine(Path.GetTempPath(), $"whisper-cookies-{Guid.NewGuid():N}.txt");
                IReadOnlyList<CoreWebView2Cookie> cookies = await _webView.CoreWebView2.CookieManager.GetCookiesAsync(_webView.Source?.ToString() ?? _startUrl);

                if (cookies.Count == 0)
                {
                    MessageBox.Show(this, GlobalResources.GetString("messageNoLoginCookies"), GlobalResources.GetString("titleLoginRequired"), MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    return;
                }

                await File.WriteAllTextAsync(cookieFilePath, BuildNetscapeCookieFile(cookies));
                string userAgent = await GetUserAgentAsync();

                _result = new BrowserLoginResult
                {
                    CookieFilePath = cookieFilePath,
                    RefererUrl = _webView.Source?.ToString() ?? _startUrl,
                    UserAgent = userAgent,
                };

                DialogResult = DialogResult.OK;
            }
            catch (Exception exception)
            {
                MessageBox.Show(this, exception.Message, GlobalResources.GetString("titleLoginExportError"), MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void ButtonCancel_Click(object? sender, EventArgs e)
        {
            DialogResult = DialogResult.Cancel;
        }

        private async Task<string> GetUserAgentAsync()
        {
            string scriptResult = await _webView.CoreWebView2.ExecuteScriptAsync("navigator.userAgent");
            return JsonSerializer.Deserialize<string>(scriptResult) ?? string.Empty;
        }

        private static string BuildNetscapeCookieFile(IEnumerable<CoreWebView2Cookie> cookies)
        {
            List<string> lines =
            [
                "# Netscape HTTP Cookie File",
                "# Generated by WhisperWinForms WebView2 login",
            ];

            foreach (CoreWebView2Cookie cookie in cookies)
            {
                string domain = cookie.IsHttpOnly ? $"#HttpOnly_{cookie.Domain}" : cookie.Domain;
                string includeSubdomains = cookie.Domain.StartsWith('.') ? "TRUE" : "FALSE";
                string secure = cookie.IsSecure ? "TRUE" : "FALSE";
                string expiration = cookie.Expires != DateTime.MinValue ? new DateTimeOffset(cookie.Expires).ToUnixTimeSeconds().ToString(CultureInfo.InvariantCulture) : "0";
                lines.Add(string.Join("\t", domain, includeSubdomains, cookie.Path, secure, expiration, cookie.Name, cookie.Value));
            }

            return string.Join(Environment.NewLine, lines) + Environment.NewLine;
        }
    }
}
